---
- name: Create the CA root certificate
  become: yes
  become_user: "{{ user }}"
  shell: > 
    openssl req
    -new -x509 -extensions v3_ca
    -config {{ ca_dir }}/{{ ca_root_dir }}/openssl.cnf
    -key {{ ca_dir }}/{{ ca_root_dir }}/private/{{ root_key }}
    -days {{ days_valid }}
    -{{ crypto_hash }}
    -out {{ ca_dir }}/{{ ca_root_dir }}/certs/{{ root_cert }}
    -subj "/C={{ cert_C }}/ST={{ cert_ST }}/L={{ cert_L }}/O={{ cert_O }}/OU={{ cert_OU }}/CN={{ root_cert_CN }}"
  args:
    creates: "{{ ca_dir }}/{{ ca_root_dir }}/certs/{{ root_cert }}" 

- name: Set permissions on CA root private key
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ ca_dir }}/{{ ca_root_dir }}/private/{{ root_key }}"
    state: file
    mode: 0600
