---
- name: Create the CA root private key
  become: yes
  shell: > 
    openssl genrsa
    -out {{ ca_dir }}/{{ ca_root_dir }}/private/{{ root_key }}
    4096
  args:
    creates: "{{ ca_dir }}/{{ ca_root_dir }}/private/{{ root_key }}" 

- name: Set permissions on CA root private key
  become: yes
  file:
    path: "{{ ca_dir }}/{{ ca_root_dir }}/private/{{ root_key }}"
    state: file
    mode: 0600
