---
- name: Create CA root and sub directories
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ ca_dir }}/{{ item[0] }}/{{ item[1] }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
  with_nested:
    - [ "{{ ca_root_dir }}", "{{ ca_int_dir }}" ]
    - "{{ ca_sub_dirs }}"

- name: Create certificate database
  become: yes
  become_user: "{{ user }}"
  copy:
    content: ''
    dest: "{{ ca_dir }}/{{ item }}/index.txt"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
    force: no
  with_items:
    - "{{ ca_root_dir }}"
    - "{{ ca_int_dir }}"

- name: Initialize serial number database
  become: yes
  become_user: "{{ user }}"
  copy:
    content: 1000
    dest: "{{ ca_dir }}/{{ item }}/serial"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
    force: no
  with_items:
    - "{{ ca_root_dir }}"
    - "{{ ca_int_dir }}"

- name: Install openssl.cnf
  become: yes
  become_user: "{{ user }}"
  template:
    src: ca/openssl.cnf.j2
    dest: "{{ ca_dir }}/{{ item.0 }}/openssl.cnf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
  with_together:
    - [ "{{ ca_root_dir }}", "{{ ca_int_dir }}" ]
    - [ "{{ root_key }}", "{{ int_key }}" ]
    - [ "{{ root_cert }}", "{{ int_cert }}" ]
